-- ccLinux package database (pacman mirror).
--
-- This file is the "repo" that `pacman -Sy` fetches from GitHub:
--   https://raw.githubusercontent.com/vanyachickenganidanya-lgtm/pacmanlinuxcraftos/main/packages.lua
--
-- It MUST `return` a plain array of package tables. Fields:
--   name      string           package name (required)
--   ver       string           e.g. "3.3.2-1"
--   desc      string           short description
--   depends   table of string  dependencies (optional; may stay unresolvable)
--   commands  table of string  /usr/bin commands the package "installs"
--   isize     number           installed size in KiB (cosmetic)
--   groups    table of string  e.g. { "base" } — MUST be present, even if {}
--
-- / База пакетов ccLinux (зеркало pacman).
-- Этот файл тянет `pacman -Sy` с GitHub. Формат — массив таблиц (поля выше).
-- Чтобы добавить пакет:
--   1. добавьте запись сюда;
--   2. (опционально) объявите его команды в linux/extra.lua через needpkg();
--   3. обновите install.lua:  make build
--   4. push в main — зеркало подхватит файл автоматически.

return {
    {
        name = "htop",
        ver = "3.3.2-1",
        desc = "Interactive process viewer",
        depends = { "ncurses" },
        commands = { "htop" },
        isize = 120,
        groups = {},
    },
    {
        name = "neofetch",
        ver = "7.1.0-2",
        desc = "A CLI system information tool",
        depends = { "bash" },
        commands = { "neofetch", "fastfetch", "screenfetch" },
        isize = 40,
        groups = {},
    },
    {
        name = "fastfetch",
        ver = "2.27.1-1",
        desc = "A feature-rich and fast system info tool",
        depends = {},
        commands = { "fastfetch", "neofetch" },
        isize = 90,
        groups = {},
    },
    {
        name = "vim",
        ver = "9.1.0785-1",
        desc = "Vi Improved",
        depends = { "ncurses" },
        commands = { "vim", "vi" },
        isize = 1800,
        groups = {},
    },
    {
        name = "nano",
        ver = "8.2-1",
        desc = "Pico editor clone with enhancements",
        depends = { "ncurses" },
        commands = { "nano" },
        isize = 200,
        groups = {},
    },
    {
        name = "git",
        ver = "2.47.0-1",
        desc = "the fast distributed version control system",
        depends = { "curl", "expat", "perl" },
        commands = { "git" },
        isize = 2200,
        groups = {},
    },
    {
        name = "cowsay",
        ver = "3.04-4",
        desc = "Configurable talking cow",
        depends = { "perl" },
        commands = { "cowsay" },
        isize = 20,
        groups = {},
    },
    {
        name = "fortune-mod",
        ver = "3.22.0-1",
        desc = "The Fortune Cookie Program",
        depends = {},
        commands = { "fortune" },
        isize = 1500,
        groups = {},
    },
    {
        name = "python",
        ver = "3.12.7-1",
        desc = "The Python 3 language",
        depends = { "bzip2", "expat", "zlib" },
        commands = { "python", "python3" },
        isize = 12000,
        groups = {},
    },
    {
        name = "gcc",
        ver = "14.2.1-1",
        desc = "The GNU Compiler Collection",
        depends = { "binutils", "gcc-libs" },
        commands = { "gcc", "g++" },
        isize = 45000,
        groups = {},
    },
    {
        name = "make",
        ver = "4.4.1-2",
        desc = "GNU make utility",
        depends = { "glibc" },
        commands = { "make" },
        isize = 400,
        groups = {},
    },
    {
        name = "binutils",
        ver = "2.43-1",
        desc = "A set of programs to assemble and manipulate binary and object files",
        depends = { "glibc", "zlib" },
        commands = { "ld", "as", "strip", "objdump" },
        isize = 8000,
        groups = {},
    },
    {
        name = "base-devel",
        ver = "1-2",
        desc = "Basic tools to build Arch Linux packages",
        depends = { "autoconf", "automake", "binutils", "gcc", "make", "pacman", "sudo" },
        commands = {},
        isize = 2,
        groups = { "base-devel" },
    },
    {
        name = "wget",
        ver = "1.24.5-3",
        desc = "Network utility to retrieve files from the Web",
        depends = { "openssl" },
        commands = { "wget" },
        isize = 300,
        groups = {},
    },
    {
        name = "openssh",
        ver = "9.9p1-1",
        desc = "Premier connectivity tool for remote login with the SSH protocol",
        depends = { "openssl", "zlib" },
        commands = { "ssh", "sshd", "scp" },
        isize = 1200,
        groups = {},
    },
    {
        name = "tmux",
        ver = "3.5-1",
        desc = "A terminal multiplexer",
        depends = { "libevent", "ncurses" },
        commands = { "tmux" },
        isize = 400,
        groups = {},
    },
    {
        name = "screen",
        ver = "4.9.1-1",
        desc = "Full-screen window manager that multiplexes a physical terminal",
        depends = { "ncurses" },
        commands = { "screen" },
        isize = 500,
        groups = {},
    },
    {
        name = "zip",
        ver = "3.0-11",
        desc = "Compressor/archiver for creating and modifying zipfiles",
        depends = { "bzip2" },
        commands = { "zip" },
        isize = 150,
        groups = {},
    },
    {
        name = "unzip",
        ver = "6.0-21",
        desc = "For extracting and viewing files in .zip archives",
        depends = { "bzip2" },
        commands = { "unzip" },
        isize = 140,
        groups = {},
    },
    {
        name = "tree",
        ver = "2.1.3-1",
        desc = "A directory listing program displaying a depth indented list of files",
        depends = { "glibc" },
        commands = { "tree" },
        isize = 40,
        groups = {},
    },
    {
        name = "strace",
        ver = "6.11-1",
        desc = "A diagnostic, debugging and instructional userspace tracer",
        depends = { "libunwind" },
        commands = { "strace" },
        isize = 300,
        groups = {},
    },
    {
        name = "gdb",
        ver = "15.2-1",
        desc = "The GNU Debugger",
        depends = { "ncurses", "python", "expat" },
        commands = { "gdb" },
        isize = 8000,
        groups = {},
    },
    {
        name = "nmap",
        ver = "7.95-1",
        desc = "Utility for network discovery and security auditing",
        depends = { "openssl" },
        commands = { "nmap" },
        isize = 6000,
        groups = {},
    },
    {
        name = "nginx",
        ver = "1.26.2-1",
        desc = "Lightweight HTTP server and IMAP/POP3 proxy server",
        depends = { "openssl", "pcre2", "zlib" },
        commands = { "nginx" },
        isize = 1500,
        groups = {},
    },
    {
        name = "apache",
        ver = "2.4.62-1",
        desc = "A high performance Unix-based HTTP server",
        depends = { "openssl", "zlib" },
        commands = { "httpd", "apachectl" },
        isize = 2200,
        groups = {},
    },
    {
        name = "docker",
        ver = "27.3.1-1",
        desc = "Pack, ship and run any application as a lightweight container",
        depends = { "containerd", "runc" },
        commands = { "docker" },
        isize = 25000,
        groups = {},
    },
    {
        name = "nodejs",
        ver = "22.11.0-1",
        desc = "Evented I/O for V8 javascript",
        depends = { "openssl" },
        commands = { "node", "nodejs" },
        isize = 14000,
        groups = {},
    },
    {
        name = "rust",
        ver = "1:1.82.0-1",
        desc = "Systems programming language focused on safety, speed and concurrency",
        depends = { "gcc-libs", "curl" },
        commands = { "rustc", "cargo" },
        isize = 70000,
        groups = {},
    },
    {
        name = "go",
        ver = "2:1.23.3-1",
        desc = "Core compiler tools for the Go programming language",
        depends = {},
        commands = { "go" },
        isize = 40000,
        groups = {},
    },
    {
        name = "btop",
        ver = "1.4.0-1",
        desc = "A monitor of system resources, bpytop port",
        depends = { "gcc-libs" },
        commands = { "btop" },
        isize = 400,
        groups = {},
    },
    {
        name = "ncdu",
        ver = "2.6-1",
        desc = "Disk usage analyzer with an ncurses interface",
        depends = { "ncurses" },
        commands = { "ncdu" },
        isize = 80,
        groups = {},
    },
    {
        name = "ripgrep",
        ver = "14.1.1-1",
        desc = "A search tool that combines the usability of ag with the speed of grep",
        depends = { "gcc-libs" },
        commands = { "rg" },
        isize = 1500,
        groups = {},
    },
    {
        name = "fd",
        ver = "10.2.0-1",
        desc = "Simple, fast and user-friendly alternative to find",
        depends = { "gcc-libs" },
        commands = { "fd" },
        isize = 900,
        groups = {},
    },
    {
        name = "bat",
        ver = "0.24.0-1",
        desc = "Cat clone with syntax highlighting and git integration",
        depends = { "gcc-libs", "libgit2" },
        commands = { "bat" },
        isize = 1800,
        groups = {},
    },
    {
        name = "eza",
        ver = "0.20.7-1",
        desc = "A modern replacement for ls",
        depends = { "gcc-libs" },
        commands = { "eza" },
        isize = 700,
        groups = {},
    },
    {
        name = "fzf",
        ver = "0.56.3-1",
        desc = "Command-line fuzzy finder",
        depends = { "glibc" },
        commands = { "fzf" },
        isize = 1200,
        groups = {},
    },
    {
        name = "jq",
        ver = "1.7.1-2",
        desc = "Command-line JSON processor",
        depends = { "oniguruma" },
        commands = { "jq" },
        isize = 200,
        groups = {},
    },
    {
        name = "yay",
        ver = "12.4.2-1",
        desc = "Yet another yogurt. Pacman wrapper and AUR helper written in go",
        depends = { "pacman", "git" },
        commands = { "yay" },
        isize = 3000,
        groups = {},
    },
    {
        name = "paru",
        ver = "2.0.4-1",
        desc = "Feature packed AUR helper",
        depends = { "pacman", "git" },
        commands = { "paru" },
        isize = 2800,
        groups = {},
    },
    {
        name = "linux-headers",
        ver = "6.12.0.arch1-1",
        desc = "Headers and scripts for building modules for the Linux kernel",
        depends = { "linux" },
        commands = {},
        isize = 25000,
        groups = {},
    },
    {
        name = "linux-lts",
        ver = "6.6.63-1",
        desc = "The LTS Linux kernel and modules",
        depends = {},
        commands = {},
        isize = 75000,
        groups = {},
    },
    {
        name = "networkmanager",
        ver = "1.50.0-1",
        desc = "Network connection manager and user applications",
        depends = { "libnm", "curl" },
        commands = { "nmcli" },
        isize = 2500,
        groups = {},
    },
    {
        name = "wireguard-tools",
        ver = "1.0.20210914-2",
        desc = "next generation secure network tunnel - tools",
        depends = { "bash" },
        commands = { "wg", "wg-quick" },
        isize = 80,
        groups = {},
    },
}
